# Generated by Django 4.0.4 on 2022-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_appointment_created_at_appointment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='importance',
            field=models.IntegerField(),
        ),
    ]
