# Generated by Django 4.0.4 on 2022-04-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_alter_appointment_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
    ]
