# Generated by Django 4.0.4 on 2022-04-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_remove_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='owner',
        ),
    ]
